<a href="https://colab.research.google.com/github/AJH0625/DeepLearning-Study/blob/main/5%EC%9E%A5_%EC%98%A4%EC%B0%A8%EC%97%AD%EC%A0%84%ED%8C%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##5.4.1 곱셈계층

In [14]:
import numpy as np

In [1]:
class MulLayer:
  def __init__(self):
    self.x = None
    self.y = None

  def forward(self,x,y):
    self.x=x
    self.y=y
    out=x*y

    return out

  def backward(self,dout):
    dx = dout*self.y
    dy = dout*self.x

    return dx, dy

In [4]:
apple = 100
apple_num = 2
tax = 1.1

#계층들
mul_apple_layer=MulLayer()
mul_tax_layer=MulLayer()

#순전파
apple_price=mul_apple_layer.forward(apple, apple_num)
price=mul_tax_layer.forward(apple_price, tax)

print(price)

#역전파
dprice=1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

220.00000000000003
2.2 110.00000000000001 200


##5.4.2 덧셈 계층

In [5]:
class AddLayer:
  def __init__(self):
    pass
  
  def forward(self,x,y):
    out=x+y
    return out

  def backward(self, dout):
    dx = dout*1
    dy = dout*1
    return dx*dy

In [8]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

#계층들
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

#순전파
apple_price = mul_apple_layer.forward(apple, apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(all_price, tax)

#역전파
dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)
dapple_price= dorange_price = add_apple_orange_layer.backward(dall_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(price)
print(dapple_num, dapple, dorange, dorange_num, dtax)

715.0000000000001
121.00000000000001 2.4200000000000004 3.630000000000001 181.50000000000003 650


##5.5.1 ReLU 계층

In [11]:
class Relu:
  def __init__(self):
    self.mask=None

  def forward(self,x):
    self.mask = (x<=0)
    out = x.copy()
    out[self.mask]=0

    return out

  def backward(self, dout):
    dout[self.mask]=0
    dx=dout

    return dx

In [15]:
x=np.array([[1.0, -0.5],[-2.0,3.0]])
print(x)

mask=(x<=0)
print(mask)

[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]


##5.5.2 Sigmoid 계층

In [16]:
class Sigmoid:
  def __init__(self):
    self.out = None
  def forward(self, x):
    out = 1 / (1 + np.exp(-x))
    self.out = out

    return out

  def backward(self, dout):
    dx = dout*(1.0 - self.out)*self.out

    return dx

##5.6.1 Affine 계층

In [18]:
X=np.random.rand(2)
W=np.random.rand(2,3)
B=np.random.rand(3)

X.shape
W.shape
B.shape

Y=np.dot(X,W)+B

##5.6.2 배치용 Affine 계층

In [19]:
X_dot_W = np.array([[0,0,0],[10,10,10]])
B=np.array([1,2,3])

X_dot_W
X_dot_W+B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [20]:
dY=np.array([[1,2,3],[4,5,6]])
dY
dB=np.sum(dY, axis=0)
dB

array([5, 7, 9])

In [21]:
class Affine:
  def __init__(self, W,b):
    self.W=W
    self.b=b
    self.x=None
    self.dW=None
    self.db=None
  
  def forward(self,x):
    self.x=x
    out=np.dot(x, self.W) + self.b

    return out

  def backward(self, dout):
    dx = np.dout(dout, self.W.T)
    self.dW = np.dot(self.x.T, dout)
    self.db = np.sum(dout, axis=0)

    return dx

##5.6.3 Softmax-with-Loss 계층

In [ ]:
class SoftmaxWithLoss:
  def __init__(self):
    self.loss = None
    self.y=None
    self.t=None

  def forward(self,x,t):
    self.t=t
    self.y=softmax(x)
    self.loss=cross_entropy_error(self.y, self.t)
    return self.loss

  def backward(self, dout=1):
    batch_size = self.t.shape[0]
    dx= (self.y=self.t) / batch_size

    return dx